CREATE TABLE users (
    user_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider           VARCHAR(10)  NOT NULL,
    provider_id        VARCHAR(100) NOT NULL,
    email              VARCHAR(255),
    nickname           VARCHAR(50)  NOT NULL,
    pref_radius_km     INT          NOT NULL DEFAULT 5,
    alarm_enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    alarm_cooldown_min INT          NOT NULL DEFAULT 30,
    created_at         TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_provider UNIQUE (provider, provider_id)
);
